In [6]:
import pandas as pd
import numpy as np
import sys
import schedule
import time


In [8]:
train_data = pd.read_csv(r"C:\Users\johns\Documents\NNandML\OpenSet\Project\CSCI-736\Experiments\mnist_train.csv")
test_data = pd.read_csv(r"C:\Users\johns\Documents\NNandML\OpenSet\Project\CSCI-736\Experiments\mnist_test.csv")

# train_data.head()
test_data.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      7    0    0    0    0    0    0    0    0    0  ...      0      0   
1      2    0    0    0    0    0    0    0    0    0  ...      0      0   
2      1    0    0    0    0    0    0    0    0    0  ...      0      0   
3      0    0    0    0    0    0    0    0    0    0  ...      0      0   
4      4    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [9]:
training_features=train_data.drop('label',axis=1)

training_features.head()

1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  1x10  ...  28x19  28x20  \
0    0    0    0    0    0    0    0    0    0     0  ...      0      0   
1    0    0    0    0    0    0    0    0    0     0  ...      0      0   
2    0    0    0    0    0    0    0    0    0     0  ...      0      0   
3    0    0    0    0    0    0    0    0    0     0  ...      0      0   
4    0    0    0    0    0    0    0    0    0     0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 784 columns]

In [10]:
training_labels=train_data['label']

training_labels.head()

0    5
1    0
2    4
3    1
4    9
Name: label, dtype: int64

In [11]:
testing_features=test_data.drop('label',axis=1)

testing_features.head()

1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  1x10  ...  28x19  28x20  \
0    0    0    0    0    0    0    0    0    0     0  ...      0      0   
1    0    0    0    0    0    0    0    0    0     0  ...      0      0   
2    0    0    0    0    0    0    0    0    0     0  ...      0      0   
3    0    0    0    0    0    0    0    0    0     0  ...      0      0   
4    0    0    0    0    0    0    0    0    0     0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 784 columns]

In [12]:
testing_labels=test_data['label']

testing_labels.head()

0    7
1    2
2    1
3    0
4    4
Name: label, dtype: int64

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [14]:
scaled_training_features = scaler.fit_transform(training_features)
scaled_testing_features = scaler.transform(testing_features)


In [15]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [16]:
model.fit(scaled_training_features, training_labels)

GaussianNB()

In [20]:
from sklearn.metrics import classification_report, confusion_matrix
original_predictions = model.predict(scaled_testing_features)
print(confusion_matrix(testing_labels, original_predictions))
print(classification_report(testing_labels, original_predictions))

[[ 828    0    1    7    2    5   19    0   89   29]
 [   1 1067    0    0    1    0    7    0   50    9]
 [ 110   16  182  103    7    5  254    3  330   22]
 [  40   24    4  282    1    3   34    7  505  110]
 [  23    2    3    4  129    5   31    5  273  507]
 [  55   15    1   16    2   29   27    2  645  100]
 [  17   11    3    1    1    5  877    0   42    1]
 [   0   11    2    9    5    1    5  201   74  720]
 [  12   53    3    6    2   11   10    1  684  192]
 [   4    5    3    6    0    0    1    9   20  961]]
              precision    recall  f1-score   support

           0       0.76      0.84      0.80       980
           1       0.89      0.94      0.91      1135
           2       0.90      0.18      0.29      1032
           3       0.65      0.28      0.39      1010
           4       0.86      0.13      0.23       982
           5       0.45      0.03      0.06       892
           6       0.69      0.92      0.79       958
           7       0.88      0.20   

In [17]:
import joblib

joblib.dump(model, 'trained_model.pkl')

['trained_model.pkl']

In [18]:
loaded_model = joblib.load('trained_model.pkl')

In [21]:
print(confusion_matrix(testing_labels, original_predictions))
print(classification_report(testing_labels, original_predictions))

[[ 828    0    1    7    2    5   19    0   89   29]
 [   1 1067    0    0    1    0    7    0   50    9]
 [ 110   16  182  103    7    5  254    3  330   22]
 [  40   24    4  282    1    3   34    7  505  110]
 [  23    2    3    4  129    5   31    5  273  507]
 [  55   15    1   16    2   29   27    2  645  100]
 [  17   11    3    1    1    5  877    0   42    1]
 [   0   11    2    9    5    1    5  201   74  720]
 [  12   53    3    6    2   11   10    1  684  192]
 [   4    5    3    6    0    0    1    9   20  961]]
              precision    recall  f1-score   support

           0       0.76      0.84      0.80       980
           1       0.89      0.94      0.91      1135
           2       0.90      0.18      0.29      1032
           3       0.65      0.28      0.39      1010
           4       0.86      0.13      0.23       982
           5       0.45      0.03      0.06       892
           6       0.69      0.92      0.79       958
           7       0.88      0.20   

In [22]:


original_predictions = model.predict(scaler.transform(testing_features))

modified_testing_features = testing_features.copy()
# start_time = datetime.datetime.now().time()
# Iterate over each image index in the original_predictions array
for image_index, original_prediction in np.ndenumerate(original_predictions):
    # Modify each pixel of the image one by one and test it
    for row in range(28):
        for col in range(28):
            pixel_index = row * 28 + col

            # Create a temporary copy of the image with the modified pixel value
            temp_modified_image = modified_testing_features.iloc[image_index[0]]
            temp_modified_image[pixel_index] = temp_modified_image[pixel_index] + 1
            

            # Scale the modified image
            scaled_temp_modified_image = scaler.transform([temp_modified_image])

            # Test the modified image
            modified_prediction = model.predict(scaled_temp_modified_image)
            print(original_prediction, modified_prediction)
            if original_prediction != modified_prediction:
                # save original pic
                # save modified pic
                temp_modified_image.to_csv("Modified_image.csv")
                testing_features.iloc[image_index[0]].to_csv("Original_image.csv")
                print( "Modifying pixel: Row: ", row, ", Column:", col, "in image: ", image_index, "to pixel_val+1 changes the prediction from: ", original_prediction, "to: ", modified_prediction )
                sys.exit(0)

            temp_modified_image = modified_testing_features.iloc[image_index[0]]
            temp_modified_image[pixel_index] = temp_modified_image[pixel_index] - 1
            

            # Scale the modified image
            scaled_temp_modified_image = scaler.transform([temp_modified_image])

            # Test the modified image
            modified_prediction = model.predict(scaled_temp_modified_image)
            print(original_prediction, modified_prediction)
            if original_prediction != modified_prediction:
                # save original pic
                # save modified pic
                temp_modified_image.to_csv("Modified_image.csv")
                testing_features.iloc[image_index[0]].to_csv("Original_image.csv")
                print( "Modifying pixel: Row: ", row, ", Column:", col, "in image: ", image_index, "to pixel_val-1 changes the prediction from: ", original_prediction, "to: ", modified_prediction )
                sys.exit(0)
            schedule.run_pending()
            



9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [9]
9 [2]
Modifying pixel: Row:  0 , Column: 15 in image:  (0,) to pixel_val+1 changes the prediction from:  9 to:  [2]


c:\Users\johns\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\johns\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\johns\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\johns\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\johns\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\johns\Anaco

SystemExit: 0

c:\Users\johns\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py:3513: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [49]:
def funk():
    print("a'rgi")
schedule.every(1).minutes.do(funk)


Every 1 minute do funk() (last run: [never], next run: 2023-04-24 20:09:12)